# Generated by Django 5.0.3 on 2024-03-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_cocktail_cooking_method_cocktail_compound_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_favorites',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='cocktails.cocktail'),
        ),
    ]
