# Generated by Django 5.0.3 on 2024-03-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_my_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_favorites',
        ),
    ]
