# Generated by Django 5.0.3 on 2024-03-15 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='Cooking_method',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='compound',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_cocktails', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredient',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
