# Generated by Django 5.0.3 on 2024-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_cocktail_cooking_method_cocktail_compound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cocktails_images/'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
