# Generated by Django 5.0.3 on 2024-03-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_cocktail_image_cocktail_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='Cooking_method',
            new_name='cooking_method',
        ),
    ]
