# Generated by Django 5.0.3 on 2024-03-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_cocktail_category_favorite_cocktail_my_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
