# Generated by Django 5.0.3 on 2024-04-01 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cocktails.cocktail'),
        ),
    ]
